# Generated by Django 5.0 on 2026-04-20 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='_encrypted_diagnosis',
            field=models.BinaryField(blank=True, db_column='encrypted_diagnosis', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='_encrypted_notes',
            field=models.BinaryField(blank=True, db_column='encrypted_notes', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='_encrypted_prescription',
            field=models.BinaryField(blank=True, db_column='encrypted_prescription', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='_encrypted_data',
            field=models.BinaryField(blank=True, db_column='encrypted_data', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='MedicalRecordAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=20)),
                ('patient_searched', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('accessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='records.medicalrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
